version: "3.8"

services:
  ml_service:
    build: .
    ports:
      - "8989:8000"
    volumes:
      - .:/app
      - ./models:/app/models  # Volumen compartido para modelos
      - /app/.venv  # Evita que el entorno virtual sea sobrescrito
    command: ["/app/.venv/bin/python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  jupyter:
    image: jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter_work:/home/jovyan/work  # Volumen para guardar los archivos de Jupyter
      - ./models:/home/jovyan/work/models  # Asegurar que los modelos sean compartidos
    command: ["start-notebook.sh", "--NotebookApp.token=''", "--NotebookApp.password=''"]  
